---
title: "Explore violations by year for EPA Region 01"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}

library(flexdashboard)
library(readr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(sf)
library(DT)
library(maps)

```


```{r notes, include=FALSE}

# see: https://towardsdatascience.com/in-r-shiny-when-is-an-error-really-an-error-702205ebb5d5
# https://www.davidsolito.com/post/conditional-drop-down-in-shiny/

```



```{r global, include=FALSE}

violations <- read_csv("violation_2019-10-06_08-03-23.zip", 
                       col_types = cols(.default = "c"))

violations <- violations %>% 
  rename_all(~ sub("VIOLATION.", "", names(violations))) %>% 
  mutate(COMPL_PER_BEGIN_DATE = dmy(COMPL_PER_BEGIN_DATE)) %>% 
  mutate(YEAR = year(COMPL_PER_BEGIN_DATE)) %>% 
  filter(PRIMACY_AGENCY_CODE != "01")

locations <- st_read("epa01_watersystems.geojson", 
                     stringsAsFactors = FALSE)

states <- map_data("state") %>% 
  filter(region %in% c("connecticut", "maine", "massachusetts", 
                       "new hampshire", "rhode island", "vermont"))

contaminant_codes <- read_csv("contaminant_codes_types.csv")

# some NA CONTAMINANT_CODE, this excludes them
lookup_codes <- violations %>% 
  group_by(CONTAMINANT_CODE) %>% 
  tally(name = "CODE_N") %>% 
  inner_join(contaminant_codes, ., 
             by = c("CODE" = "CONTAMINANT_CODE")) %>% 
  arrange(TYPE_CODE, CODE) %>% 
  mutate(NAME2 = paste0(CODE, ": ", NAME, " (n = ", CODE_N, ")"))


# lookup_codes %>% select(TYPE_CODE) %>% 
#   distinct()

IOCcodes <- lookup_codes %>% filter(TYPE_CODE == "IOC") %>% .$CODE
IOCcode_names <- lookup_codes %>% filter(TYPE_CODE == "IOC") %>% .$NAME2
# names(IOCcodes) <- IOCcode_names
IOCcodes_list <- list()
for(i in 1:length(IOCcodes)) {
  IOCcodes_list[[i]] <- IOCcodes[i]
}
names(IOCcodes_list) <- IOCcode_names

MORcodes <- lookup_codes %>% filter(TYPE_CODE == "MOR") %>% .$CODE
MORcode_names <- lookup_codes %>% filter(TYPE_CODE == "MOR") %>% .$NAME2
# names(MORcodes) <- MORcode_names
MORcodes_list <- list()
for(i in 1:length(MORcodes)) {
  MORcodes_list[[i]] <- MORcodes[i]
}
names(MORcodes_list) <- MORcode_names

OCcodes <- lookup_codes %>% filter(TYPE_CODE == "OC") %>% .$CODE
OCcode_names <- lookup_codes %>% filter(TYPE_CODE == "OC") %>% .$NAME2
# names(OCcodes) <- OCcode_names
OCcodes_list <- list()
for(i in 1:length(OCcodes)) {
  OCcodes_list[[i]] <- OCcodes[i]
}
names(OCcodes_list) <- OCcode_names

RAcodes <- lookup_codes %>% filter(TYPE_CODE == "RA") %>% .$CODE
RAcode_names <- lookup_codes %>% filter(TYPE_CODE == "RA") %>% .$NAME2
# names(RAcodes) <- RAcode_names
RAcodes_list <- list()
for(i in 1:length(RAcodes)) {
  RAcodes_list[[i]] <- RAcodes[i]
}
names(RAcodes_list) <- RAcode_names

RLcodes <- lookup_codes %>% filter(TYPE_CODE == "RL") %>% .$CODE
RLcode_names <- lookup_codes %>% filter(TYPE_CODE == "RL") %>% .$NAME2
# names(RLcodes) <- RLcode_names
RLcodes_list <- list()
for(i in 1:length(RLcodes)) {
  RLcodes_list[[i]] <- RLcodes[i]
}
names(RLcodes_list) <- RLcode_names

WQcodes <- lookup_codes %>% filter(TYPE_CODE == "WQ") %>% .$CODE
WQcode_names <- lookup_codes %>% filter(TYPE_CODE == "WQ") %>% .$NAME2
# names(WQcodes) <- WQcode_names
WQcodes_list <- list()
for(i in 1:length(WQcodes)) {
  WQcodes_list[[i]] <- WQcodes[i]
}
names(WQcodes_list) <- WQcode_names


ContGroup_list <- list(`IOC` = IOCcodes_list, 
                       `MOR` = MORcodes_list,
                       `OC` = OCcodes_list,
                       `RA` = RAcodes_list,
                       `RL` = RLcodes_list,
                       `WQ` = WQcodes_list)

# way to name these items
# c(`this` = ContGroup_list[["WQ"]][[10]])

YEAR_range <- seq(min(violations$YEAR), max(violations$YEAR), by = 1)


```



Column {.sidebar}
-----------------------------------------------------------------------


```{r violations, echo=FALSE}
inputPanel(
  selectInput("code", label = "Contaminant code:",
              choices = ContGroup_list, selected = "1005", selectize = FALSE),
  selectInput("type", label = "Health-based:",
              choices = c("Y", "N"), selected = "Y"),
  selectInput("year", label = "Map and table year:",
              choices = c(YEAR_range), selected = 2010)
  
)
```

</br>

+ Data from SDWIS Violation table download 2019-10-06
+ Contaminant codes are grouped by type and show name
+ Might be best to start with health-based, then update contaminant dropdown to only show available
+ Need better error handling for null queries
+ Slider for year range for line graph might be nice

Column {data-width=650}
-----------------------------------------------------------------------

### Line graph

```{r ggline}

renderPlot({
  
  plotdata <- violations %>% filter(CONTAMINANT_CODE == input$code, 
                           IS_HEALTH_BASED_IND == input$type) %>% 
  group_by(PRIMACY_AGENCY_CODE, YEAR) %>% 
  tally()
  
  
  ggplot(plotdata, aes(x = YEAR, y = n, 
                       color = PRIMACY_AGENCY_CODE)) + 
    geom_line(size = 1.5) + 
    ylab("# violations") +
    theme(legend.position = "top",
          panel.grid.minor.x = element_blank()) +
    guides(color = guide_legend(nrow = 1)) + 
    scale_x_continuous(breaks = seq(min(plotdata$YEAR), 
                                    max(plotdata$YEAR), by = 1))
  
 
})

```

### Violations Table

```{r}

renderDataTable({
  
  tabledata <- violations %>% 
    filter(CONTAMINANT_CODE == input$code, 
           IS_HEALTH_BASED_IND == input$type, 
           YEAR == input$year) %>% 
    arrange(PRIMACY_AGENCY_CODE, PWSID)
  
  datatable(tabledata, options = list(
    pageLength = 25, 
    scrollX = TRUE,
    scrollY = "200px",
    initComplete = JS("function(settings, json) {$(this.api().table().header()).css({'font-size' : '12px'});}")
  )) %>% 
    formatStyle(colnames(tabledata), fontSize = '12px')
})

```


Column {data-width=650}
-----------------------------------------------------------------------

### Map of violations (Town/City/System locations)


```{r map}

renderPlot({
  
  mapdata <- violations %>% 
    filter(CONTAMINANT_CODE == input$code, 
           IS_HEALTH_BASED_IND == input$type,
           YEAR == input$year) %>% 
    select(PWSID) %>% 
    mutate(IND = 1) %>% 
    distinct() %>% 
    inner_join(locations, ., by = "PWSID")
  
  mapdata <- cbind(st_drop_geometry(mapdata), 
                   st_coordinates(mapdata))
  
  ggplot(states, aes(x = long, y = lat, group = group)) + 
  geom_polygon(fill = NA, color = "black") + 
  geom_jitter(data = mapdata, 
             aes(x = X, y = Y),
             width = 0.001, height = 0.001,
             alpha = 0.7, color = "red", inherit.aes = FALSE) + 
  coord_fixed(1.2) +
  theme(panel.border = element_rect(fill = NA, color = "black"),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
  
})


```

